import React from 'react';
import { useLocation } from 'react-router-dom';

const Legal: React.FC = () => {
  const { pathname } = useLocation();
  const type = pathname.replace('/', '');
  
  const content = {
    privacy: {
      title: "Privacy Policy",
      text: "At Tools Genie AI, we prioritize your privacy. We do not store personal input data from our tools. All processing is done either client-side or via secure, transient API calls. We use cookies for analytics to improve user experience."
    },
    terms: {
      title: "Terms of Service",
      text: "By using Tools Genie AI, you agree to use the tools responsibly. We are not liable for any data loss or inaccuracies generated by the AI tools. These tools are provided 'as is' for educational and professional assistance."
    },
    disclaimer: {
      title: "Disclaimer",
      text: "The tools provided on this website are for informational purposes only. While we strive for accuracy, Tools Genie AI makes no warranties regarding the completeness or reliability of the results. Always verify critical data."
    }
  };

  const current = content[type as keyof typeof content] || content.privacy;

  return (
    <div className="max-w-3xl mx-auto py-12">
      <h1 className="text-4xl font-bold mb-8">{current.title}</h1>
      <div className="prose prose-invert prose-lg">
        <p>{current.text}</p>
        <p className="mt-4 text-slate-400">
          Last Updated: {new Date().toLocaleDateString()}
        </p>
        <h3 className="text-xl font-bold mt-8 mb-4">Contact</h3>
        <p className="text-slate-400">
          If you have questions regarding this policy, please contact us at sivasatyap9@gmail.com.
        </p>
      </div>
    </div>
  );
};

export default Legal;
